

<canvas id="myLineChart" width="740" height="200"></canvas>

<script>

    // Add a helper to format timestamp data
    Date.prototype.formatMMDDYYYY = function() {
        return (this.getMonth() + 1) +
        "/" +  this.getDate() +
        "/" +  this.getFullYear();
    }

    var jsonData = $.ajax({
      url: '/hivetemperature/danvou',
      dataType: 'json',
    }).done(function (results) {

      // Split timestamp and data into separate arrays
      var labels = [], t1=[]; t2=[];

      for (data in results.temperatures)
      {
          var d = results.temperatures[data];
          labels.push(d.h);
          t1.push(parseFloat(d.t1));
          t2.push(parseFloat(d.t2));
      }

      // Create the chart.js data structure using 'labels' and 'data'
      var tempData = {
        labels : labels,
        datasets : [
            {
            label                 : "top bar",
            fill                  : false,
            lineTension           : 0.1,
            backgroundColor       : "rgba(75,192,192,0.4)",
            borderColor           : "rgba(75,192,192,1)",
            borderCapStyle        : 'butt',
            borderDash            : [],
            borderDashOffset      : 0.0,
            borderJoinStyle       : 'miter',
            pointBorderColor      : "rgba(75,192,192,1)",
            pointBackgroundColor  : "#fff",
            pointBorderWidth      : 1,
            pointHoverRadius       : 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor : "rgba(220,220,220,1)",
            pointHoverBorderWidth : 2,
            pointRadius           : 1,
            pointHitRadius        : 10,
            data                  : t1
            },
            {
            label                 : "entry",
            fill                  : false,
            lineTension           : 0.1,
            backgroundColor       : "rgba(0,255,0,0.4)",
            borderColor           : "rgba(0,255,0,1)",
            borderCapStyle        : 'butt',
            borderDash            : [],
            borderDashOffset      : 0.0,
            borderJoinStyle       : 'miter',
            pointBorderColor      : "rgba(0,255,0,1)",
            pointBackgroundColor  : "#fff",
            pointBorderWidth      : 1,
            pointHoverRadius       : 5,
            pointHoverBackgroundColor: "rgba(0,255,0,1)",
            pointHoverBorderColor : "rgba(220,220,220,1)",
            pointHoverBorderWidth : 2,
            pointRadius           : 1,
            pointHitRadius        : 10,
            data                  : t2
            }
        ]
      };

      // Get the context of the canvas element we want to select
      var ctx = document.getElementById("myLineChart").getContext("2d");

      var myLineChart = new Chart(ctx, {
          type: 'line',
          data: tempData
      });

    });

</script>
